[package]
name = "did"
version = "0.1.0"
authors = ["Julian Popescu <jpopesculian@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_asn1_der = "0.1"
base58 = "0.1"
hex = "0.3"
regex = "1"
lazy_static = "1"
